src/plugins/ssoclient/__init__.py
# -*- coding: utf-8 -*-
"""
    ProcessName_XXX.plugins.ssoclient
    ~~~~~~~~~~~~~~

    SSO Client

    :copyright: (c) 2017 by staugur.
    :license: MIT, see LICENSE for more details.
"""

#: Importing these two modules is the first and must be done.
#: 首先导入这两个必须模块
from __future__ import absolute_import
from libs.base import PluginBase
#: Import the other modules here, and if it's your own module, use the relative Import. eg: from .lib import Lib
#: 在这里导入其他模块, 如果有自定义包目录, 使用相对导入, 如: from .lib import Lib
import requests, json
from config import SSO
from utils.web import login_required, anonymous_required, set_ssoparam, set_sessionId, get_redirect_url, get_referrer_url
from utils.tool import url_check, logger, comma_pat, hmac_sha256
from flask import Blueprint, request, jsonify, g, redirect, url_for, make_response

#：Your plugin name
#：你的插件名称
__name__        = "ssoclient"
#: Plugin describes information
#: 插件描述信息
__description__ = "SSO Client"
#: Plugin Author
#: 插件作者
__author__      = "Mr.tao <staugur@saintic.com>"
#: Plugin Version
#: 插件版本
__version__     = "0.1.0"
#: Plugin Url
#: 插件主页
__url__         = "https://www.saintic.com"
#: Plugin License
#: 插件许可证
__license__     = "MIT"
#: Plugin License File
#: 插件许可证文件
__license_file__= "LICENSE"
#: Plugin Readme File
#: 插件自述文件
__readme_file__ = "README"
#: Plugin state, enabled or disabled, default: enabled
#: 插件状态, enabled、disabled, 默认enabled
__state__       = "enabled"

# 定义sso server地址并删除SSO多余参数
sso_server = SSO.get("sso_server").strip("/")
if not url_check(sso_server):
    raise

# 定义请求函数
def sso_request(url, params=None, data=None, timeout=5, num_retries=1):
    """
    @params dict: 请求查询参数
    @data dict: 提交表单数据
    @timeout int: 超时时间，单位秒
    @num_retries int: 超时重试次数
    """
    headers = {"User-Agent": "Mozilla/5.0 (X11; CentOS; Linux i686; rv:7.0.1406) Gecko/20100101 PassportClient/{}".format(__version__)}
    try:
        resp = requests.post(url, params=params, headers=headers, timeout=timeout, data=data).json()
    except requests.exceptions.Timeout,e:
        if num_retries > 0:
            return sso_request(url, params=params, data=data, timeout=timeout, num_retries=num_retries-1)
    else:
        return resp

# 定义蓝图
sso_blueprint = Blueprint("sso", "sso")
@sso_blueprint.route("/Login")
@anonymous_required
def Login():
    """ Client登录地址，需要跳转到SSO Server上 """
    ReturnUrl = request.args.get("ReturnUrl") or get_referrer_url() or url_for("front.index_view", _external=True)
    if url_check(sso_server):
        NextUrl = "{}/sso/?sso={}".format(sso_server, set_ssoparam(ReturnUrl))
        return redirect(NextUrl)
    else:
        return "Invalid Configuration"

@sso_blueprint.route("/Logout")
@login_required
def Logout():
    """ Client注销地址，需要跳转到SSO Server上 """
    ReturnUrl = request.args.get("ReturnUrl") or get_referrer_url() or url_for("front.index_view", _external=True)
    NextUrl = "{}/signOut?ReturnUrl={}".format(sso_server, ReturnUrl)
    return redirect(NextUrl)

@sso_blueprint.route("/authorized", methods=["GET", "POST"])
def authorized():
    """ Client SSO 单点登录、注销入口, 根据`Action`参数判断是`ssoLogin`还是`ssoLogout` """
    Action = request.args.get("Action")
    if Action == "ssoLogin":
        # 单点登录
        ticket = request.args.get("ticket")
        if request.method == "GET" and ticket and g.signin == False:
            resp = sso_request("{}/sso/validate".format(sso_server), dict(Action="validate_ticket"), dict(ticket=ticket, app_name=SSO["app_name"], get_userinfo=False, get_userbind=False))
            logger.debug("SSO check ticket resp: {}".format(resp))
            if resp and isinstance(resp, dict) and "success" in resp and "uid" in resp:
                if resp["success"] is True:
                    uid = resp["uid"]
                    sid = resp["sid"]
                    expire = int(resp["expire"])
                    #userinfo = resp["userinfo"].get("data")
                    allowUsers = [ i for i in comma_pat.split(g.site["sso_AllowedUsers"]) if i ]
                    allowLogin = False
                    if allowUsers:
                        if uid and uid in allowUsers:
                            allowLogin = True
                    else:
                        allowLogin = True
                    if allowLogin is True:
                        # 授权令牌验证通过，设置局部会话，允许登录
                        sessionId = set_sessionId(uid=uid, seconds=expire, sid=sid)
                        response = make_response(redirect(get_redirect_url("front.index_view")))
                        response.set_cookie(key="sessionId", value=sessionId, max_age=expire, httponly=True, secure=False if request.url_root.split("://")[0] == "http" else True)
                        return response
    elif Action == "ssoLogout":
        # 单点注销
        ReturnUrl = request.args.get("ReturnUrl") or get_referrer_url() or url_for("front.index_view", _external=True)
        NextUrl   = "{}/signOut?ReturnUrl={}".format(sso_server, ReturnUrl)
        app_name  = request.args.get("app_name")
        if request.method == "GET" and NextUrl and app_name and g.signin == True and app_name == SSO["app_name"]:
            response = make_response(redirect(NextUrl))
            response.set_cookie(key="sessionId", value="", expires=0)
            return response
    elif Action == "ssoConSync":
        # 数据同步：参数中必须包含大写的hmac_sha256(app_name:app_id:app_secret)的signature值
        signature = request.args.get("signature")
        if request.method == "POST" and signature and signature == hmac_sha256("{}:{}:{}".format(SSO["app_name"], SSO["app_id"], SSO["app_secret"])).upper():
            try:
                data = json.loads(request.form.get("data"))
                ct = data["CallbackType"]
                cd = data["CallbackData"]
                uid = data["uid"]
                token = data["token"]
            except Exception,e:
                logger.warning(e)
            else:
                logger.info("ssoConSync with uid: {} -> {}: {}".format(uid, ct, cd))
                resp = sso_request("{}/sso/validate".format(sso_server), dict(Action="validate_sync"), dict(token=token, uid=uid))
                logger.debug("ssoCronSync resp: {}".format(resp))
                if resp and isinstance(resp, dict) and resp.get("success") is True:
                    # 之后根据不同类型的ct处理cd
                    logger.debug("ssoConSync is ok")
                    return jsonify(msg="Synchronization completed", success=True, app_name=SSO["app_name"])
    return "Invalid Authorized"

#: 返回插件主类
def getPluginClass():
    return SSOClientMain

#: 插件主类, 不强制要求名称与插件名一致, 保证getPluginClass准确返回此类
class SSOClientMain(PluginBase):

    def register_bep(self):
        """注册蓝图入口, 返回蓝图路由前缀及蓝图名称"""
        bep = {"prefix": "/sso", "blueprint": sso_blueprint}
        return bep

src/views/FrontView.py
# -*- coding: utf-8 -*-
"""
    CherryWaterfall.views.FrontView
    ~~~~~~~~~~~~~~

    The blueprint for front view.

    :copyright: (c) 2017 by staugur.
    :license: MIT, see LICENSE for more details.
"""

import os, datetime
from config import GLOBAL, Upyun, SYSTEM
from utils.web import login_required, apilogin_required
from utils.Signature import Signature
from utils.upyunstorage import CloudStorage
from utils.tool import logger, md5, gen_rnd_filename, allowed_file, get_current_timestamp, ListEqualSplit, setSystem, timestamp_to_timestring, comma_pat
from werkzeug import secure_filename
from werkzeug.contrib.atom import AtomFeed
from flask import Blueprint, request, g, redirect, make_response, url_for, jsonify, render_template, abort, current_app
from random import randint

# 初始化前台蓝图
FrontBlueprint = Blueprint("front", __name__)
# 初始化签名
sig = Signature()
# 初始化又拍云存储封装接口
api = CloudStorage(timeout=60)

@FrontBlueprint.route("/")
@login_required
def index_view():
    """主页视图"""
    if g.site.get("sys_Close") in ("1", 1):
        return abort(400)
    return render_template("index.html")

@FrontBlueprint.route("/admin/")
@login_required
def admin_view():
    """控制台视图"""
    return render_template("admin.html")

@FrontBlueprint.route('/upload/', methods=['POST','OPTIONS'])
@apilogin_required
@sig.signature_required
def upload_view():
    res = dict(code=-1, msg=None)
    label = request.args.get("label")
    _has_label = lambda label: g.redis.sismember(current_app.config["labelKey"], label) and g.redis.exists("{}:label:{}".format(GLOBAL['ProcessName'], label)) or label == current_app.config["labelDefault"]
    if not label:
        label = current_app.config["labelDefault"]
    if label and _has_label(label):
        f = request.files.get('file')
        if f and allowed_file(f.filename):
            filename = secure_filename(gen_rnd_filename() + "." + f.filename.split('.')[-1]) #随机命名
            basedir = Upyun['basedir'] if Upyun['basedir'].startswith('/') else "/" + Upyun['basedir']
            imgUrl = os.path.join(basedir, filename)
            try:
                upres = api.put(imgUrl, f.stream.read())
            except Exception,e:
                logger.error(e, exc_info=True)
                res.update(code=2, msg="Storage failure")
            else:
                imgId = md5(filename)
                imgUrl = Upyun['dn'].strip("/") + imgUrl
                upres.update(ctime=get_current_timestamp(), imgUrl=imgUrl, imgId=imgId, label=label)
                try:
                    pipe = g.redis.pipeline()
                    pipe.sadd(current_app.config["picKey"], imgId)
                    pipe.hmset("{}:{}".format(GLOBAL['ProcessName'], imgId), upres)
                    pipe.hincrby("{}:label:{}".format(GLOBAL['ProcessName'], label), "imgNum")
                    pipe.execute()
                except Exception,e:
                    logger.error(e, exc_info=True)
                    res.update(code=0, msg="It has been uploaded, but the server has encountered an unknown error")
                else:
                    logger.info("Upload to Upyun file saved, its url is %s, result is %s, imgId is %s" %(imgUrl, upres, imgId))
                    res.update(code=0, imgUrl=imgUrl)
        else:
            res.update(code=1, msg="Unsuccessfully obtained file or format is not allowed")
    else:
        res.update(code=2, msg="Invalid label")
    logger.info(res)
    return jsonify(res)

@FrontBlueprint.route("/api/", methods=['GET', 'POST','OPTIONS', 'DELETE', 'PUT'])
@apilogin_required
@sig.signature_required
def api_view():
    """获取图片数据(以redis为基准)"""
    res = dict(code=-1, msg=None)
    Action = request.args.get("Action")
    # 公共函数
    _get_pics = lambda: [ g.redis.hgetall("{}:{}".format(GLOBAL['ProcessName'], imgId)) for imgId in list(g.redis.smembers(current_app.config["picKey"])) ]
    _get_label = lambda: [ g.redis.hgetall("{}:label:{}".format(GLOBAL['ProcessName'], label)) for label in list(g.redis.smembers(current_app.config["labelKey"])) ]
    _has_label = lambda label: g.redis.sismember(current_app.config["labelKey"], label) and g.redis.exists("{}:label:{}".format(GLOBAL['ProcessName'], label))
    def _set_label(label, user):
        """新建标签"""
        try:
            pipe = g.redis.pipeline()
            pipe.sadd(current_app.config["labelKey"], label)
            pipe.hmset("{}:label:{}".format(GLOBAL['ProcessName'], label), dict(user=user, ctime=get_current_timestamp(), label=label))
            pipe.execute()
        except Exception,e:
            logger.error(e, exc_info=True)
            return False
        else:
            return True
    def _del_label(label):
        """删除标签"""
        imgNum = int(g.redis.hget("{}:label:{}".format(GLOBAL['ProcessName'], label), "imgNum") or 0)
        if imgNum > 0:
            return False
        try:
            pipe = g.redis.pipeline()
            pipe.srem(current_app.config["labelKey"], label)
            pipe.delete("{}:label:{}".format(GLOBAL['ProcessName'], label))
            pipe.execute()
        except Exception,e:
            logger.error(e, exc_info=True)
            return False
        else:
            return True
    # GET请求段
    if request.method == "GET":
        if Action == "getList":
            # 获取图片列表
            sort = request.args.get("sort") or "desc"
            page = request.args.get("page") or 0
            limit = request.args.get("limit") or 10
            label = request.args.get("label")
            # 参数检查
            try:
                page = int(page)
                limit = int(limit)
            except:
                res.update(code=2, msg="Invalid page or limit")
            else:
                data = _get_pics()
                if data:
                    data = sorted(data, key=lambda k:(k.get('ctime',0), k.get('imgUrl',0)), reverse=False if sort == "asc" else True)
                    if label:
                        data = [ i for i in data if i.get("label", current_app.config["labelDefault"]) == label ]
                    count = len(data)
                    data = ListEqualSplit(data, limit)
                    pageCount = len(data)
                    if page < pageCount:
                        res.update(code=0, data=data[page], pageCount=pageCount)
                    else:
                        res.update(code=3, msg="IndexOut with page {}".format(page))
                else:
                    res.update(code=4, msg="No data")
        elif Action == "getInfo":
            # 获取系统相关信息
            data = dict(site=g.site, imageNumber=g.redis.scard(current_app.config["picKey"]))
            res.update(data=data, code=0)
        elif Action == "getOne":
            # 获取随机一张图片
            res.update(data=g.redis.hgetall("{}:{}".format(GLOBAL['ProcessName'], g.redis.srandmember(current_app.config["picKey"]))), code=0)
        elif Action == "getPhoto":
            # 返回相册格式数据
            data = _get_pics()
            res = dict(title=g.site["site_TitleSuffix"], id=1, start=0, data=[ {"alt": timestamp_to_timestring(float(img['ctime'])), "pid": img["imgId"], "src": img["imgUrl"]} for img in sorted(data, key=lambda k:(k.get('ctime',0), k.get('imgUrl',0)), reverse=True) if img["imgUrl"].split(".")[-1].lower() != "mp4" ])
        elif Action == "getLabel":
            # 定义参数
            sort = request.args.get("sort") or "desc"
            try:
                data = _get_label()
                if not data:
                    data = []
                labelDefaultData = g.redis.hgetall("{}:label:{}".format(GLOBAL['ProcessName'], current_app.config["labelDefault"]))
                labelDefaultData.update(label=current_app.config["labelDefault"], user="system", ctime="")
                data.append(labelDefaultData)
                if data and isinstance(data, list):
                    data = [i for i in sorted(data, reverse=False if sort == "asc" else True)]
            except Exception,e:
                logger.error(e, exc_info=True)
                res.update(code=1, msg="Unknown error")
            else:
                res.update(code=0, data=data)
    elif request.method == "POST":
        if Action == "setSystem":
            # 更新系统配置
            data = {k: v for k, v in request.form.iteritems() if k in ("site_TitleSuffix", "site_RssTitle", "site_License", "site_Copyright", "author_Email", "github", "sys_Close", "sso_AllowedUsers", "site_UploadMax", "site_UploadSize")}
            res.update(setSystem(g.redis, current_app.config["sysKey"], **data))
        elif Action == "setLabel":
            label = request.form.get("label")
            if label and not _has_label(label):
                if _set_label(label=label, user=g.uid):
                    res.update(code=0)
                else:
                    res.update(msg="Add label failed", code=5)
            else:
                res.update(msg="Invalid label", code=6)
    elif request.method == "DELETE":
        if Action == "delLabel":
            label = request.form.get("label")
            if label and _has_label(label):
                if _del_label(label):
                    res.update(code=0)
                else:
                    res.update(msg="Del label failed", code=7)
            else:
                res.update(msg="Invalid label", code=8)
    logger.debug(res)
    return jsonify(res)


@FrontBlueprint.route("/wx/")
@sig.signature_required
def wx_view():
    """获取图片数据(以redis为基准)"""
    res = dict(code=-1, msg=None)
    Action = request.args.get("Action")
    # 公共函数
    _get_pics = lambda: [ g.redis.hgetall("{}:{}".format(GLOBAL['ProcessName'], imgId)) for imgId in list(g.redis.smembers(current_app.config["picKey"])) ]
    # GET请求段
    if request.method == "GET":
        if Action == "getList":
            # 获取图片列表
            sort = request.args.get("sort") or "desc"
            page = request.args.get("page") or 0
            limit = request.args.get("limit") or 10
            # 参数检查

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} - {{ g.site.site_TitleSuffix }}</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layui.css') }}"  media="all">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"  media="all">
    <link href="{{ url_for('static', filename='images/favicon.ico') }}" rel="icon" type="image/x-icon" />
    <link href="{{ url_for('static', filename='images/favicon.ico') }}" rel="shortcut icon" type="image/x-icon" />
    {% block head %}{% endblock %}
</head>
<body>
<ul class="layui-nav">
    <li class="layui-nav-item"><a href="{{ url_for('front.index_view') }}">主页<span class="layui-badge layui-bg-green">{%- set imgNum = g.redis.scard(picKey) %}{% if imgNum > 99 %}99+{% else %}{{ imgNum }}{% endif %}</span></a></li>
    <li class="layui-nav-item"><a href="javascript:showPhoto()">相册<span class="layui-badge-dot"></span></a></li>
    <li class="layui-nav-item"><a href="{{ url_for('front.feed_view') }}" target="_blank">订阅<span class="layui-badge-dot"></span></a></li>
    {% if g.signin %}
    <li class="layui-nav-item"><a href="{{ url_for('front.admin_view') }}">控制台</a></li>
    <li class="layui-nav-item"><a href="{{ url_for('sso.Logout') }}">注销</a></li>
    {% endif %}
</ul>
{% block content %}
{% endblock %}
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='layui.all.js') }}" charset="utf-8"></script>
<script src="{{ url_for('static', filename='js/md5.min.js') }}" charset="utf-8"></script>
<script type="text/javascript">
    function _sign(params) {
        /*
            @params object: uri请求参数(包含除signature外的公共参数)
        */
        if( typeof(params)!="object" ) {
            console.error("params is not an object");
            return false;
        }
        // NO.1 参数排序
        var _my_sorted = Object.keys(params).sort();
        // NO.2 排序后拼接字符串
        var canonicalizedQueryString = '';
        for (var _i in _my_sorted) {
            canonicalizedQueryString += _my_sorted[_i] + '=' + params[_my_sorted[_i]] + '&';
        }
        canonicalizedQueryString += "{{ Sign.accesskey_secret }}";
        // NO.3 加密返回签名: signature
        return md5(canonicalizedQueryString).toUpperCase();
    }
    function make_url(params) {
        /*
            @params object: uri请求参数(不包含公共参数)
        */
        if( typeof(params)!="object" ) {
            var params = {};
        }
        // 获取当前时间戳
        var timestamp = Math.round(new Date().getTime() / 1000 - 8).toString();
        // 设置公共参数
        var publicParams = { accesskey_id: "{{ Sign.accesskey_id }}", version: "{{ Sign.version }}", timestamp: timestamp };
        // 添加加公共参数
        for (var i in publicParams) {
            params[i] = publicParams[i];
        }
        var uri = ''
        for (var i in params) {
            uri += i + '=' + params[i] + '&';
        }
        uri += 'signature=' + _sign(params);
        //console.log(uri);
        return uri
    }
    function showPhoto() {
        var layer = layui.layer, $ = layui.jquery;
        $.getJSON("{{ url_for('front.api_view') }}?"+make_url({Action: "getPhoto"}), function(json){
            console.log(json);
            layer.photos({
                photos: json
                ,anim: 5 //0-6的选择，指定弹出图片动画类型，默认随机（请注意，3.0之前的版本用shift参数）
            });
        });
    }
</script>
{% block script %}
{% endblock %}
</body>
</html>

src/templates/footer.html
<div class="layui-footer footer footer-demo">
  <div class="layui-main">
    <p>{{ g.site.site_Copyright }} <a href="{{ url_for('front.index_view') }}">{{ request.url_root.split("://")[-1].strip("/") }}</a> {{ g.site.site_License }} LICENSE</p>
    <p>
      <a href="mailto:{{ g.site.author_Email }}">联系</a>
      <a href="{{ g.site.github }}" target="_blank" rel="nofollow">GitHub</a>
    </p>
    <p class="site-union">
      <a upyun=""><img src="https://img.saintic.com/misc/public/upyunlogo.png"></a>
    </p>
  </div>
</div>

src/templates/index.html
{% extends "base.html" %}

{% block title %}首页({{ g.redis.scard(picKey) }}){% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="/static/css/boxImg.css">
{% endblock %}

{% block content %}
    <blockquote class="layui-elem-quote">
        <i>当前位置：主页</i><br><i>当前标签：{{ request.args.get("label", "全部") }}</i><div id="listLabelArea"></div>
    </blockquote>
    <div class="container">
        <div class="waterfall" id="layImages">
        </div>
    </div>
    {% include "footer.html" %}
{% endblock %}

{% block script %}
<script type="text/javascript">
    var $ = layui.jquery, util = layui.util, flow = layui.flow, layer = layui.layer;
    //判断当前字符串是否以str开始
    if (typeof String.prototype.startsWith != 'function')   {
        String.prototype.startsWith = function (str){
            return this.slice(0, str.length) == str;
        };
    }
    //判断当前字符串是否以str结束
    if (typeof String.prototype.endsWith != 'function') {
        String.prototype.endsWith = function (str){
            return this.slice(-str.length) == str;
        };
    }
    //右下角工具
    util.fixbar();
    //加载标签列表
    $.ajax({
        url: '{{ url_for("front.api_view") }}?'+make_url({Action: "getLabel"}),
        success: function (res) {
            // 渲染标签区域
            var str = '';
            for (var index = 0, length = res.data.length; index < length ; index++) {
                str += '<a href="{{ url_for("front.index_view") }}?label='+ res.data[index].label +'"><span class="layui-badge layui-bg-green">' + res.data[index].label + '</span></a>&nbsp;&nbsp;';
            }
            $('#listLabelArea').html(str);
        },
    });
    //流加载图片
    flow.load({
        elem: '#layImages'
        ,isLazyimg: true
        ,isAuto: true
        ,done: function(page, next){ //加载下一页
            page -= 1;
            var lis = [];
            var params = {Action: "getList", page: page, limit: "{{ request.args.get('limit', 20) }}", label: "{{ request.args.get('label', '') }}"};
            $.ajax({
                url: '{{ url_for("front.api_view") }}?'+make_url(params),
                async: false,
                success: function (res) {
                    console.log(res);
                    layui.each(res.data, function(index, item){
                        // 判定imgUrl是否是视频格式文件
                        if (item.imgUrl.endsWith(".mp4")===true) {
                            lis.push('<div class="item"><video width="100%" height="100%" controls="controls" autobuffer="autobuffer"><source src="'+item.imgUrl+'" type="video/mp4"></source></video></div>');
                        } else {
                            lis.push('<div class="item"><img modal="zoomImg" src="'+item.imgUrl+'" lay-src="'+item.imgUrl+'" lay-id="'+item.imgId+'"></div>');
                        }
                    });
                    $.getScript("/static/js/boxImg.js");
                    next(lis.join(''), page < res.pageCount);
                },
            });
        }
    });
</script>
{% endblock %}